version: "3.7"

services:
  # This DB is for the FastAPI Backend.
  db:
    extends:
      file: ../backend-development/docker-compose.yaml
      service: db
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 2s
      timeout: 2s
      retries: 10

  # This DB is for Web Authentication and data caching.
  webdb:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 2s
      timeout: 2s
      retries: 10

  # This lets you manually inspect the web and backend databases.
  adminer:
    extends:
      file: ../backend-development/docker-compose.yaml
      service: adminer
  backend:
    build:
      dockerfile: docker/Dockerfile.backend
      context: ../..
    image: oasst-backend
    environment:
      - POSTGRES_HOST=db
      - ALLOW_ANY_API_KEY=True
      - MAX_WORKERS=1
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  # This fakes an SMTP email server used by website authentication.
  # User registration emails can be found by going to localhost:1080 and
  # opening the emails listed.
  maildev:
    image: maildev/maildev
    restart: always
    environment:
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "1080:1080"
      - "1025:1025"
