name: (Bot) Publish Docker Image

on:
  push:
    paths:
      - "bot/**"
    tags:
      - v*

jobs:
  build:
    uses: ./.github/workflows/docker-build.yaml
    with:
      image-name: bot
      folder: bot
      build-args: ""
