name: (Backend) Publish Docker Image

on:
  push:
    paths:
      - "backend/**"
    tags:
      - v*

jobs:
  build:
    uses: ./.github/workflows/docker-build.yaml
    with:
      image-name: backend
      folder: backend
      build-args: ""
