name: Release

on:
  release:
    types: [released]

jobs:
  build-backend:
    uses: ./.github/workflows/docker-build.yaml
    with:
      image-name: oasst-backend
      folder: backend
      build-args: ""
